### ISSUE TITLE
Installing with MSSQL using the default config, we are getting errors in RabbitMQ.

### ISSUE THREAD

**Issue by jaymuthus** [Senzing/docker-compose-demo#111]
**Describe the bug**
Installing with MSSQL using the default config, we are getting errors in RabbitMQ.

senzing-rabbitmq        | PLAIN login refused: user 'rabbitmq' - invalid credentials
senzing-rabbitmq        | 2020-08-18 07:22:30.423 [error] <0.969.0> Error on AMQP connection <0.969.0> (172.19.0.1:38822 -> 172.19.0.6:5672, state: starting):
senzing-rabbitmq        | PLAIN login refused: user 'rabbitmq' - invalid credentials
senzing-rabbitmq        | 2020-08-18 07:22:30.437 [error] <0.972.0> Error on AMQP connection <0.972.0> (172.19.0.1:38826 -> 172.19.0.6:5672, state: starting):
senzing-rabbitmq        | PLAIN login refused: user 'rabbitmq' - invalid credentials

[error-log.txt](https://github.com/Senzing/docker-compose-demo/files/5088905/error-log.txt)

**Comment by jaymuthus** [comment]
@docktermj Please take a look at this issue asap. We are blocked by this from starting the installation to Guide House.

Everything was working before 2 weeks after your last fix. But, while I retry the instructions before handing over to them, I got this issue. Please take a look. 

Let me know if you need more details.

**Comment by docktermj** [comment]
Trying to recreate using https://github.com/Senzing/docker-compose-demo/blob/master/resources/mssql/docker-compose-rabbitmq-mssql.yaml

**Comment by docktermj** [comment]
Seen in https://github.com/Senzing/docker-compose-demo/files/5088905/error-log.txt

```
senzing-rabbitmq | 2020-08-18 02:14:24.118 [info] <0.643.0> Statistics database started.
senzing-rabbitmq | 2020-08-18 02:14:24.118 [info] <0.642.0> Starting worker pool 'management_worker_pool' with 3 processes in it
senzing-rabbitmq | 2020-08-18 02:14:24.133 [info] <0.652.0> accepting AMQP connection <0.652.0> (172.19.0.1:47804 -> 172.19.0.2:5672)
senzing-rabbitmq | 2020-08-18 02:14:24.133 [info] <0.655.0> accepting AMQP connection <0.655.0> (172.19.0.1:47808 -> 172.19.0.2:5672)
senzing-rabbitmq | 2020-08-18 02:14:24.133 [info] <0.658.0> accepting AMQP connection <0.658.0> (172.19.0.1:47806 -> 172.19.0.2:5672)
senzing-rabbitmq | 2020-08-18 02:14:24.137 [error] <0.658.0> Error on AMQP connection <0.658.0> (172.19.0.1:47806 -> 172.19.0.2:5672, state: starting):
senzing-rabbitmq | PLAIN login refused: user 'rabbitmq' - invalid credentials
senzing-rabbitmq | 2020-08-18 02:14:24.137 [error] <0.655.0> Error on AMQP connection <0.655.0> (172.19.0.1:47808 -> 172.19.0.2:5672, state: starting):
senzing-rabbitmq | PLAIN login refused: user 'rabbitmq' - invalid credentials
senzing-rabbitmq | 2020-08-18 02:14:24.137 [error] <0.652.0> Error on AMQP connection <0.652.0> (172.19.0.1:47804 -> 172.19.0.2:5672, state: starting):
senzing-rabbitmq | PLAIN login refused: user 'rabbitmq' - invalid credentials
senzing-rabbitmq |  completed with 3 plugins.
senzing-rabbitmq | 2020-08-18 02:14:24.338 [info] <0.8.0> Server startup complete; 3 plugins started.
senzing-rabbitmq |  * rabbitmq_management
senzing-rabbitmq |  * rabbitmq_web_dispatch
senzing-rabbitmq |  * rabbitmq_management_agent
senzing-rabbitmq | 2020-08-18 02:14:27.138 [info] <0.652.0> closing AMQP connection <0.652.0> (172.19.0.1:47804 -> 172.19.0.2:5672)
senzing-rabbitmq | 2020-08-18 02:14:27.138 [info] <0.655.0> closing AMQP connection <0.655.0> (172.19.0.1:47808 -> 172.19.0.2:5672)
senzing-rabbitmq | 2020-08-18 02:14:27.138 [info] <0.658.0> closing AMQP connection <0.658.0> (172.19.0.1:47806 -> 172.19.0.2:5672)
senzing-rabbitmq | 2020-08-18 02:14:27.641 [info] <0.665.0> accepting AMQP connection <0.665.0> (172.19.0.1:47814 -> 172.19.0.2:5672)
senzing-rabbitmq | 2020-08-18 02:14:27.642 [info] <0.668.0> accepting AMQP connection <0.668.0> (172.19.0.1:47818 -> 172.19.0.2:5672)
senzing-rabbitmq | 2020-08-18 02:14:27.642 [info] <0.671.0> accepting AMQP connection <0.671.0> (172.19.0.1:47820 -> 172.19.0.2:5672)
senzing-rabbitmq | 2020-08-18 02:14:27.646 [error] <0.665.0> Error on AMQP connection <0.665.0> (172.19.0.1:47814 -> 172.19.0.2:5672, state: starting):
senzing-rabbitmq | PLAIN login refused: user 'rabbitmq' - invalid credentials
senzing-rabbitmq | 2020-08-18 02:14:27.646 [error] <0.671.0> Error on AMQP connection <0.671.0> (172.19.0.1:47820 -> 172.19.0.2:5672, state: starting):
senzing-rabbitmq | PLAIN login refused: user 'rabbitmq' - invalid credentials
senzing-rabbitmq | 2020-08-18 02:14:27.646 [error] <0.668.0> Error on AMQP connection <0.668.0> (172.19.0.1:47818 -> 172.19.0.2:5672, state: starting):
senzing-rabbitmq | PLAIN login refused: user 'rabbitmq' - invalid credentials
```

Seen in recreation attempt:
```

2020-08-18 14:17:53.395 [info] <0.641.0> Statistics database started.
2020-08-18 14:17:53.395 [info] <0.640.0> Starting worker pool 'management_worker_pool' with 3 processes in it
 completed with 3 plugins.
2020-08-18 14:17:53.557 [info] <0.8.0> Server startup complete; 3 plugins started.
 * rabbitmq_management
 * rabbitmq_web_dispatch
 * rabbitmq_management_agent
2020-08-18 14:18:06.913 [info] <0.664.0> accepting AMQP connection <0.664.0> (192.168.0.8:56136 -> 192.168.0.6:5672)
2020-08-18 14:18:06.921 [info] <0.664.0> connection <0.664.0> (192.168.0.8:56136 -> 192.168.0.6:5672): user 'user' authenticated and granted access to vhost '/'
2020-08-18 14:18:06.935 [info] <0.680.0> accepting AMQP connection <0.680.0> (192.168.0.8:56140 -> 192.168.0.6:5672)
2020-08-18 14:18:06.939 [info] <0.680.0> connection <0.680.0> (192.168.0.8:56140 -> 192.168.0.6:5672): user 'user' authenticated and granted access to vhost '/'
2020-08-18 14:18:06.954 [info] <0.691.0> accepting AMQP connection <0.691.0> (192.168.0.8:56144 -> 192.168.0.6:5672)
2020-08-18 14:18:06.958 [info] <0.691.0> connection <0.691.0> (192.168.0.8:56144 -> 192.168.0.6:5672): user 'user' authenticated and granted access to vhost '/'
2020-08-18 14:18:06.980 [info] <0.702.0> accepting AMQP connection <0.702.0> (192.168.0.8:56148 -> 192.168.0.6:5672)
2020-08-18 14:18:06.984 [info] <0.702.0> connection <0.702.0> (192.168.0.8:56148 -> 192.168.0.6:5672): user 'user' authenticated and granted access to vhost '/'
2020-08-18 14:18:12.518 [info] <0.664.0> closing AMQP connection <0.664.0> (192.168.0.8:56136 -> 192.168.0.6:5672, vhost: '/', user: 'user')
2020-08-18 14:18:12.520 [info] <0.680.0> closing AMQP connection <0.680.0> (192.168.0.8:56140 -> 192.168.0.6:5672, vhost: '/', user: 'user')
2020-08-18 14:18:12.522 [info] <0.702.0> closing AMQP connection <0.702.0> (192.168.0.8:56148 -> 192.168.0.6:5672, vhost: '/', user: 'user')
2020-08-18 14:18:12.522 [info] <0.691.0> closing AMQP connection <0.691.0> (192.168.0.8:56144 -> 192.168.0.6:5672, vhost: '/', user: 'user')
2020-08-18 14:18:35.915 [info] <0.750.0> accepting AMQP connection <0.750.0> (192.168.0.10:47462 -> 192.168.0.6:5672)
2020-08-18 14:18:35.919 [info] <0.756.0> accepting AMQP connection <0.756.0> (192.168.0.10:47466 -> 192.168.0.6:5672)
2020-08-18 14:18:35.921 [info] <0.750.0> connection <0.750.0> (192.168.0.10:47462 -> 192.168.0.6:5672): user 'user' authenticated and granted access to vhost '/'
```

So in the error condition, it appears that the login user is `rabbitmq`, but in the recreation, the login user is `user`.   So the question is:  "Why?"

@jaymuthus Just to make sure we're working with the same level of `bitnami/rabbitmq:3.8.2`, can you run the following on the machine having the error:

```console
docker pull bitnami/rabbitmq:3.8.2
```

I'm showing this SHA on download:
```
Digest: sha256:f6a30ae08cc6efdeeee3d06fdc24255b9963f4de871c8612a72ba149cf58cab5
```

**Comment by docktermj** [comment]
@jaymuthus Are you using the following definition of the `rabbitmq:` service:

https://github.com/Senzing/docker-compose-demo/blob/ed5b4f5530732946e23f88b617d6c3b95af2c363/resources/mssql/docker-compose-rabbitmq-mssql.yaml#L31-L45

Or are you running with modifications?

**Comment by docktermj** [comment]
In https://github.com/Senzing/docker-compose-demo/files/5088905/error-log.txt it does look like `user` is also used.

```
senzing-rabbitmq | 2020-08-18 02:14:36.405 [info] <0.701.0> accepting AMQP connection <0.701.0> (172.19.0.8:60118 -> 172.19.0.2:5672)
senzing-rabbitmq | 2020-08-18 02:14:36.410 [info] <0.701.0> connection <0.701.0> (172.19.0.8:60118 -> 172.19.0.2:5672): user 'user' authenticated and granted access to vhost '/'
```

**Comment by docktermj** [comment]
@jaymuthus You may also have a different issue.   In https://github.com/Senzing/docker-compose-demo/files/5088905/error-log.txt this is seen:

```
senzing-stream-loader | 2020-08-18 02:15:03,512 senzing-50010890E G2Engine.addRecord() Exception: 9000E|LIMIT: Maximum number of records ingested: 100000; JSON: {"ADDR_CITY": "Dlalas", "ADDR_LINE1": "788 Alma ST", "ADDR_POSTAL_CODE": "75215", "ADDR_STATE": "TX", "CC_ACCOUNT_NUMBER": "50185881568895705", "DATA_SOURCE": "TEST", "DATE_OF_BIRTH": "6/2/1952", "DRIVERS_LICENSE_NUMBER": "V995121498988", "DRIVERS_LICENSE_STATE": "MD", "DSRC_ACTION": "A", "ENTITY_TYPE": "TEST", "GENDER": "N/A", "NAME_LAST": "THOMPSON", "PHONE_NUMBER": "347-4506", "RECORD_ID": "181734352", "SSN_NUMBER": "501-27-9836", "entityid": "181734352", "srccode": "MDMPER"}
```

Looks like you don't have a sufficient Senzing license at `/etc/opt/senzing/g2.lic`.  (a.k.a `${SENZING_ETC_DIR}/g2.lic` on the failing machine.)

**Comment by docktermj** [comment]
In https://github.com/Senzing/docker-compose-demo/files/5088905/error-log.txt it does look records are getting into the RabbitMQ queue:
```
senzing-stream-producer | 2020-08-18 02:14:38,316 senzing-50140104D Thread: Process-0-FilterQueueDictToJsonRabbitmqThread-0 Records sent to queue: 3000
senzing-stream-producer | 2020-08-18 02:14:38,935 senzing-50140104D Thread: Process-0-FilterQueueDictToJsonRabbitmqThread-2 Records sent to queue: 4000
```

And it does look like records are being consumed from the queue:
```
senzing-stream-loader | 2020-08-18 02:15:03,512 senzing-50010890E G2Engine.addRecord() Exception: 9000E|LIMIT: Maximum number of records ingested: 100000; JSON: {"ADDR_CITY": "Dlalas", "ADDR_LINE1": "788 Alma ST", "ADDR_POSTAL_CODE": "75215", "ADDR_STATE": "TX", "CC_ACCOUNT_NUMBER": "50185881568895705", "DATA_SOURCE": "TEST", "DATE_OF_BIRTH": "6/2/1952", "DRIVERS_LICENSE_NUMBER": "V995121498988", "DRIVERS_LICENSE_STATE": "MD", "DSRC_ACTION": "A", "ENTITY_TYPE": "TEST", "GENDER": "N/A", "NAME_LAST": "THOMPSON", "PHONE_NUMBER": "347-4506", "RECORD_ID": "181734352", "SSN_NUMBER": "501-27-9836", "entityid": "181734352", "srccode": "MDMPER"}
```

So I think your base problem is the Senzing license at `/etc/opt/senzing/g2.lic`

**Comment by jaymuthus** [comment]
I see the following about the lic:
senzing-stream-loader   | 2020-08-18 19:22:21,371 senzing-50010160I -------------------- LICENSE --------------------
senzing-stream-loader   | 2020-08-18 19:22:21,371 senzing-50010161I           Version: 2.0.1 (2020-07-23)
senzing-stream-loader   | 2020-08-18 19:22:21,371 senzing-50010162I          Customer: 
senzing-stream-loader   | 2020-08-18 19:22:21,372 senzing-50010163I              Type: EVAL
senzing-stream-loader   | 2020-08-18 19:22:21,372 senzing-50010164I   Expiration date: 2021-01-22
senzing-stream-loader   | 2020-08-18 19:22:21,375 senzing-50010165I   Expiration time: 156 days until expiration
senzing-stream-loader   | 2020-08-18 19:22:21,375 senzing-50010166I           Records: 100000
senzing-stream-loader   | 2020-08-18 19:22:21,376 senzing-50010167I          Contract: 
senzing-stream-loader   | 2020-08-18 19:22:21,376 senzing-50010299I -------------------------------------------------
senzing-stream-loader   | 2020-08-18 19:22:21,425 senzing-50010123I Total     memory:     15598817280 bytes
senzing-stream-loader   | 2020-08-18 19:22:21,425 senzing-50010124I Available memory:     11947094016 bytes
senzing-stream-loader   | 2020-08-18 19:22:21,680 senzing-50010140I System Resources:
senzing-stream-loader   | 2020-08-18 19:22:21,681 senzing-50010141I     Physical cores: 2
senzing-stream-loader   | 2020-08-18 19:22:21,681 senzing-50010142I      Logical cores: 4
senzing-stream-loader   | 2020-08-18 19:22:21,682 senzing-50010143I       Total Memory: 14.5 GB
senzing-stream-loader   | 2020-08-18 19:22:21,682 senzing-50010144I   Available Memory: 11.1 GB
senzing-stream-loader   | 2020-08-18 19:22:21,682 senzing-50010145I Resource requested:
senzing-stream-loader   | 2020-08-18 19:22:21,682 senzing-50010146I                     Processes: 1
senzing-stream-loader   | 2020-08-18 19:22:21,682 senzing-50010147I           Threads per process: 4
senzing-stream-loader   | 2020-08-18 19:22:21,682 senzing-50010148I     Minimum recommended cores: 1
senzing-stream-loader   | 2020-08-18 19:22:21,682 senzing-50010149I    Minimum recommended memory: 4.5 GB
senzing-redoer          | 2020-08-18 19:22:22,204 senzing-50100160I -------------------- LICENSE --------------------
senzing-redoer          | 2020-08-18 19:22:22,204 senzing-50100161I           Version: 2.0.1 (2020-07-23)
senzing-redoer          | 2020-08-18 19:22:22,204 senzing-50100162I          Customer: 
senzing-redoer          | 2020-08-18 19:22:22,204 senzing-50100163I              Type: EVAL
senzing-redoer          | 2020-08-18 19:22:22,204 senzing-50100164I   Expiration date: 2021-01-22
senzing-redoer          | 2020-08-18 19:22:22,207 senzing-50100165I   Expiration time: 156 days until expiration
senzing-redoer          | 2020-08-18 19:22:22,207 senzing-50100166I           Records: 100000
senzing-redoer          | 2020-08-18 19:22:22,208 senzing-50100167I          Contract:

**Comment by jaymuthus** [comment]
This is after a fresh installation

**Comment by jaymuthus** [comment]
But still, seeing the error

senzing-rabbitmq        | PLAIN login refused: user 'rabbitmq' - invalid credentials
senzing-rabbitmq        | 2020-08-18 19:22:24.449 [error] <0.859.0> Error on AMQP connection <0.859.0> (172.19.0.1:42498 -> 172.19.0.3:5672, state: starting):
senzing-rabbitmq        | PLAIN login refused: user 'rabbitmq' - invalid credentials
senzing-rabbitmq        | 2020-08-18 19:22:24.449 [error] <0.865.0> Error on AMQP connection <0.865.0> (172.19.0.1:42500 -> 172.19.0.3:5672, state: starting):
senzing-rabbitmq        | PLAIN login refused: user 'rabbitmq' - invalid credentials

**Comment by jaymuthus** [comment]
i see the following too as you said.
senzing-rabbitmq        | 2020-08-18 19:22:24.760 [info] <0.872.0> connection <0.872.0> (172.19.0.11:59618 -> 172.19.0.3:5672): user 'user' authenticated and granted access to vhost '/'
senzing-rabbitmq        | 2020-08-18 19:22:24.761 [info] <0.878.0> connection <0.878.0> (172.19.0.11:59622 -> 172.19.0.3:5672): user 'user' authenticated and granted access to vhost '/'
senzing-rabbitmq        | 2020-08-18 19:22:24.761 [info] <0.869.0> connection <0.869.0> (172.19.0.11:59616 -> 172.19.0.3:5672): user 'user' authenticated and granted access to vhost '/'

**Comment by jaymuthus** [comment]
Any idea, why is it attempting to connect as "rabbitmq" and how to resolve it?

**Comment by jaymuthus** [comment]
In case, if you can't reproduce, please let me know if we can spend like 30mins tomorrow in the morning before 10AM PST.
I will show you and you can help with this.

Thanks for your time and help on this @docktermj

**Comment by docktermj** [comment]
@jaymuthus 

The license seen is the "evaluation" license that only supports 100,000 records.  
```
senzing-stream-loader | 2020-08-18 19:22:21,375 senzing-50010166I Records: 100000
```
Errors in the log suggest you are trying to insert more than 100K records.  You need to insert a license that supports more than the complimentary 100K records.


The errors seen in the `senzing-rabbitmq` log suggest that there is some other process that is trying to login as username "rabbitmq".   From what I can see, there are no processes in the docker-compose.yaml file that are trying to access RabbitMQ as user "rabbitmq".   Do you have another process that is accessing RabbitMQ?

**Comment by jaymuthus** [comment]
@docktermj Yes, in that machine, it seems another team has installed a BPM software and that was trying to login using the user rabbitmq. So, we can mark it resolved.
