### ISSUE TITLE
Use latest container image releases

### ISSUE THREAD

**Issue by vincentytran** [Senzing/docker-compose-demo#133]
Is it possible to have the docker-compose yaml scripts use the latest releases of all the senzing containers?

Right now they have the version number hard coded and it is an older release (e.g. senzing-api-server 2.0.1).

**Comment by docktermj** [comment]
@vincentytran  We've updated all of the docker-compose formations with the latest version via https://github.com/Senzing/docker-compose-demo/issues/134

However, I'm keeping this issue open to remind us to demonstrate how to specify versions by using `export` statements like this:

```
export SENZING_DOCKER_IMAGE_VERSION_ADMINER=1.0.0
export SENZING_DOCKER_IMAGE_VERSION_APT=1.0.4
export SENZING_DOCKER_IMAGE_VERSION_DB2_DRIVER_INSTALLER=1.0.2
export SENZING_DOCKER_IMAGE_VERSION_ENTITY_SEARCH_WEB_APP=2.1.1
export SENZING_DOCKER_IMAGE_VERSION_ENVIRONMENT=1.1.3
export SENZING_DOCKER_IMAGE_VERSION_INIT_CONTAINER=1.5.10
export SENZING_DOCKER_IMAGE_VERSION_JUPYTER=1.2.0
export SENZING_DOCKER_IMAGE_VERSION_PHPPGADMIN=1.0.0
export SENZING_DOCKER_IMAGE_VERSION_PORTAINER=latest
export SENZING_DOCKER_IMAGE_VERSION_POSTGRES=11.6
export SENZING_DOCKER_IMAGE_VERSION_POSTGRESQL_CLIENT=1.0.0
export SENZING_DOCKER_IMAGE_VERSION_RABBITMQ=3.8.2
export SENZING_DOCKER_IMAGE_VERSION_REDOER=1.3.3
export SENZING_DOCKER_IMAGE_VERSION_RESOLVER=1.3.1
export SENZING_DOCKER_IMAGE_VERSION_SENZING_API_SERVER=2.2.1
export SENZING_DOCKER_IMAGE_VERSION_SENZING_CONSOLE=1.0.0
export SENZING_DOCKER_IMAGE_VERSION_SENZING_DEBUG=1.3.5
export SENZING_DOCKER_IMAGE_VERSION_SQLITE_WEB=latest
export SENZING_DOCKER_IMAGE_VERSION_SSHD=1.0.0
export SENZING_DOCKER_IMAGE_VERSION_STREAM_LOADER=1.6.4
export SENZING_DOCKER_IMAGE_VERSION_STREAM_LOGGER=1.1.2
export SENZING_DOCKER_IMAGE_VERSION_STREAM_PRODUCER=1.2.3
export SENZING_DOCKER_IMAGE_VERSION_XTERM=1.0.3
export SENZING_DOCKER_IMAGE_VERSION_YUM=1.1.3
```

In the meantime,  if you do export an environment variable with a docker image version it will be used in the docker formation.  For example:

```
export SENZING_DOCKER_IMAGE_VERSION_SENZING_API_SERVER=2.2.0
```

will override the value seen at https://github.com/Senzing/docker-compose-demo/blob/581fb092425d1f4b9609ee0743d737dc6af32b12/resources/postgresql/docker-compose-rabbitmq-postgresql.yaml#L208

**Comment by docktermj** [comment]
Latest versions:

```
export SENZING_DOCKER_IMAGE_VERSION_ADMINER=1.0.0
export SENZING_DOCKER_IMAGE_VERSION_APT=1.0.4
export SENZING_DOCKER_IMAGE_VERSION_DB2_DRIVER_INSTALLER=1.0.2
export SENZING_DOCKER_IMAGE_VERSION_ENTITY_SEARCH_WEB_APP=2.1.1
export SENZING_DOCKER_IMAGE_VERSION_ENVIRONMENT=1.2.2
export SENZING_DOCKER_IMAGE_VERSION_INIT_CONTAINER=1.6.3
export SENZING_DOCKER_IMAGE_VERSION_JUPYTER=1.2.0
export SENZING_DOCKER_IMAGE_VERSION_PHPPGADMIN=1.0.0
export SENZING_DOCKER_IMAGE_VERSION_PORTAINER=latest
export SENZING_DOCKER_IMAGE_VERSION_POSTGRES=11.6
export SENZING_DOCKER_IMAGE_VERSION_POSTGRESQL_CLIENT=1.0.0
export SENZING_DOCKER_IMAGE_VERSION_RABBITMQ=3.8.2
export SENZING_DOCKER_IMAGE_VERSION_REDOER=1.3.4
export SENZING_DOCKER_IMAGE_VERSION_RESOLVER=1.3.1
export SENZING_DOCKER_IMAGE_VERSION_SENZING_API_SERVER=2.3.0
export SENZING_DOCKER_IMAGE_VERSION_SENZING_CONSOLE=1.0.0
export SENZING_DOCKER_IMAGE_VERSION_SENZING_DEBUG=1.3.5
export SENZING_DOCKER_IMAGE_VERSION_SQLITE_WEB=latest
export SENZING_DOCKER_IMAGE_VERSION_SSHD=1.0.2
export SENZING_DOCKER_IMAGE_VERSION_STREAM_LOADER=1.6.5
export SENZING_DOCKER_IMAGE_VERSION_STREAM_LOGGER=1.1.2
export SENZING_DOCKER_IMAGE_VERSION_STREAM_PRODUCER=1.2.3
export SENZING_DOCKER_IMAGE_VERSION_SWAGGERAPI_SWAGGER_UI=latest
export SENZING_DOCKER_IMAGE_VERSION_XTERM=1.0.3
export SENZING_DOCKER_IMAGE_VERSION_YUM=1.1.3
```

**Comment by docktermj** [comment]
@vincentytran  Here's where we're at:

In our "docker-compose.yaml" files, we'll be specifying versions of docker containers that have undergone testing.   Note that I say "docker-compose.yaml" files, it is a generic term for all of the `.yaml` files in https://github.com/Senzing/docker-compose-demo/tree/master/resources.  These versions may not be the latest, but they will have been tested together.

As you probably know, using the `:latest` version at the end of a docker image URL does not guarantee the latest version of the docker image.  It merely checks to see if you have a `:latest` in your local repository.  If it does, it uses it without checking if there's a newer version.

We are keeping a consolidated list of current versions at https://github.com/Senzing/knowledge-base/blob/master/lists/version-dependencies.md#latest-versions   The `export` statements can be run on the command line before issuing the `docker-compose up` command.   These environment variables will over-ride the versions seen in the "docker-compose.yaml" file by using something akin to "Linux Shell Parameter Expansion".

Is this sufficient for your use?

**Comment by vincentytran** [comment]
Yes that addresses the issue and that page with the latest version is what I needed. Please close the issue.
