### ISSUE TITLE
Regarding the disk size increase in the application server

### ISSUE THREAD

**Issue by jaymuthus-consilienz** [Senzing/docker-compose-demo#141]
We have the postgresql db in one server and all the remaining senzing docker containers in another server say app server.
We see lots of "core.*" files in the folder "/opt/senzing/g2/python" as below:

2.9G	core.11713
5.4G	core.20064
2.4G	core.24103
2.7G	core.24142
3.3G	core.24426
2.6G	core.25178
2.9G	core.25253
1.9G	core.25668

This is occupying around 35G. Can we remove all these files when there is no upload in progress. OR do we need retain these files for any reason?

**Comment by docktermj** [comment]
@jaymuthus-consilienz   From my vantage point, they are core dumps that can be removed.  But I'm seeking additional opinions from some of our folks at Senzing.  I'll post when I get more information.

**Comment by jaymuthus-consilienz** [comment]
@docktermj Thanks for your quick response. For now, we will remove from the back up folders. After your final confirmation, we will remove from the current folders.

**Comment by barrycaceres** [comment]
the core files are indicative of a problem that occurred and could provide a way to diagnose the problem.  how recent are the timestamps on the core files?  i am wondering if they were created when running a prior version of Senzing or with the current 2.2.5 version.

removing them should not affect Senzing’s operation in the least, but it might prevent us from diagnosing what caused them to be created.

- Barry Caceres

Sent from my iPad

On Nov 26, 2020, at 8:01 PM, jaymuthus-consilienz <notifications@github.com> wrote:

﻿

@docktermj<https://github.com/docktermj> Thanks for your quick response. For now, we will remove from the back up folders. After your final confirmation, we will remove from the current folders.

**Comment by docktermj** [comment]
Got a tip from @brianmacy.  To help us debug, do something like the following:

```console
gdb python3 core.20064
bt
```
I hope I got that right.

Attach the output so we can debug.

**Comment by docktermj** [comment]
@jaymuthus-consilienz   Is this still an issue?   If not, would you be kind enough to close the issue.   If it is still an issue,  what else can we do to help?

**Comment by jaymuthus-consilienz** [comment]
Thanks @docktermj. I am closing it now.
