### ISSUE TITLE
RE: MSSQL Driver

### ISSUE THREAD

**Issue by vijayaramanr** [Senzing/docker-compose-demo#194]
Hi Team,

We followed this instruction https://github.com/Senzing/docker-compose-demo/blob/master/docs/docker-compose-rabbitmq-mssql/README.md to install senzing with MSSQL. But, we didn't receive mssql-tools and mssql folder in the folder and it throws error like the following screenshot. Please review it and support us. Thanks!

![error](https://user-images.githubusercontent.com/49683425/124785545-938ac180-df64-11eb-9390-da92bc55ddf6.png)

**Comment by docktermj** [comment]
Looking at it.  Will be trying to recreate.

**Comment by vijayaramanr** [comment]
Hi Michael,
I followed all the above instructions and installed senzing and MSSQL driver. But it throws errors like the attachment., when i trying to connect mssql and not able to perform port forward in my local env.

We are using AWS REDHAT. Please review and support me/

![image](https://user-images.githubusercontent.com/49683425/124912254-5af1f300-e00b-11eb-908a-ae5a767a067a.png)

**Comment by docktermj** [comment]
@ryanbasile Do you know if this may be one of the famous RedHat networking issues?

**Comment by docktermj** [comment]
Hi @vijayaramanr!

Are you running RHEL 7 or 8?

**Comment by vijayaramanr** [comment]
NAME="Red Hat Enterprise Linux"
VERSION="8.4 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.4"

**Comment by docktermj** [comment]
Hi @vijayaramanr!

According to RedHat's site:

> Docker is not supported in RHEL 8. 

Reference:   https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/building_running_and_managing_containers/index#con_running-containers-without-docker_assembly_starting-with-containers

**Comment by vijayaramanr** [comment]
Yes Brian, But docker showing active status in above server

![image](https://user-images.githubusercontent.com/49683425/124930187-be395080-e01e-11eb-8be6-ce511d845318.png)
 and review sending container status here
![image](https://user-images.githubusercontent.com/49683425/124930437-f5a7fd00-e01e-11eb-8501-3e542c311299.png)

And same senzing with postgres is working well in the another server (same os and configuration)

**Comment by brianmacy** [comment]
Vijay,

Yes, I realize it "kind of" functions.  But it isn't supported and doesn't work for our docker images.  It doesn't matter which docker images you are using from Senzing, they won't work.

As Michael points out, even RedHat says docker is not supported on RedHat 8.

**Comment by vijayaramanr** [comment]
yes, Brian and Michael. Could you please share the steps to uninstall current docker, dockercompose and senzing and to install the senzing with MSSQL in Redhat8?

**Comment by vijayaramanr** [comment]
My Doubt is: I have another server for my development with REDHAT 8 and it's working fine. Am facing this issue in this server only.

**Comment by brianmacy** [comment]
Vijay,

We don't support it and RedHat doesn't support it.  You can try Docker's instructions for CentOS8 (https://docs.docker.com/engine/install/centos/)  but there is no certainty that will work.

If you want a Docker install that works then switch to CentOS/RHEL 7, Debian/Ubuntu, or Amazon Linux 2.

**Comment by vijayaramanr** [comment]
Okay, let us try this instruction and get back to you.

**Comment by rvijayram** [comment]
Thanks, Michael and Brian. We can close this ticket. We configured the senzing with docker in RHEL 7. Its working well for us. But we have to find the solution for RHEL 8

**Comment by vijayaramanr** [comment]
Thanks, Michael and Brian. We have created a new server with RHEL 7 and configured everything successfully. It's working well for us. But we have to find the solution for RHEL-8. We can close this ticket now. Thank you so much.
