### ISSUE TITLE
New mount point for postgresql persistence

### ISSUE THREAD

**Issue by docktermj** [Senzing/docker-compose-demo#223]
Bitnami has changed the mountpoint for persisting data.  Adjust all docker-compose.yaml files to reflect this change.

### References:

1. https://github.com/bitnami/bitnami-docker-postgresql/blob/master/README.md#persisting-your-database

**Comment by antaenc** [comment]
Modifying the yaml to the new mount point as per the link works.

**Comment by docktermj** [comment]
Pull Requests:

- https://github.com/Senzing/docker-compose-demo/pull/254
