### ISSUE TITLE
Instruction s need to state the docker-compose must be v1.29

### ISSUE THREAD

**Issue by echasin** [Senzing/docker-compose-demo#262]
**What is the URL of the documentation?**

https://github.com/Senzing/docker-compose-demo/blob/main/docs/docker-compose-rabbitmq-postgresql/README.md

**What can be improved?**
--Prerequisites  

The yaml files to build the solution  throw an error with docker-compose version 1.25  on the element below.  Earlier versions of docker-compose throw error on "name:"

`networks:
  senzing:
    name: ${SENZING_DOCKER_NETWORK:-senzing-network}`

docker-compose version 1.29  fixes the issue

**Additional context**

**Comment by docktermj** [comment]
@echasin Thank you for reporting this.  I'll take care of it early next week.

**Comment by docktermj** [comment]
Pull Requests:

- https://github.com/Senzing/docker-compose-demo/pull/263

**Comment by docktermj** [comment]
@echasin We've updated the documentation.  If it is to you liking, would you be kind enough to close it issue.  (if not, please let us know what more we can do.)

If we don't hear from you in a week, we'll go ahead and close this issue.

**Comment by echasin** [comment]
Thanks for updating.  Closing issue.
