### ISSUE TITLE
Remove "Pull docker images" section of README.md

### ISSUE THREAD

**Issue by docktermj** [Senzing/docker-compose-demo#66]
The "Pull docker images" is superfluous.

1. The *docker-compose.yaml* file will pull the docker images
2. The list can become out-of-date if not meticulously manged.
3. There is no functional difference if the list is removed.
4. Removes chance of accidental sudo timeout

**Comment by ryanbasile** [comment]
4. Removing the pull prevents an accidental sudo timeout.

**Comment by docktermj** [comment]
Pull Requests:

1. https://github.com/Senzing/docker-compose-demo/pull/67
