### ISSUE TITLE
senzing/mysql-init, repository does not exist

### ISSUE THREAD

**Issue by LRSutton** [Senzing/docker-compose-demo#85]
**Describe the bug**
Dependence on non-existent library

While running `docker-compose up`, the following error occurred:

ERROR: pull access denied for senzing/mysql-init, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**To Reproduce**
Executing `docker-compose up` using docker-compose version 

docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.17
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018

Linux x 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Expected behavior**
docker-compose should have completed creation of the mysqlinit container without error.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by docktermj** [comment]
Hi @LRSutton!

Because we aren't legally able to re-distribute the mysql client,  we have our customers build this particular Docker image.

We document how to do this in places like this:  https://github.com/Senzing/docker-compose-demo/tree/master/docs/docker-compose-rabbitmq-mysql#build-docker-images

Was there a set of instructions that you were following that did not have this information?   If so, please let us know, we'd like to correct it.

**Comment by LRSutton** [comment]
Hey there Michael,

Yes, most of the demos I've been working on today have struggled with the
database drivers. Normally I'd install them separately but in the many of
the docker containers, the permissions have been adjusted so that
additional installs break. (I thought this was me misunderstanding the
delivery approach so I didn't document the issue or pursue it further.).
I'll take a look at the instructions you linked to.

Thank you!
- Lorin

**Comment by docktermj** [comment]
@LRSutton If there are any instructions or techniques that will make installing database drivers easier, please let us know.  We look forward to improving our instructions.

**Comment by docktermj** [comment]
@LRSutton We'll follow up on this at https://github.com/Senzing/docker-web-app-demo/issues/34  

Please close this issue if you are OK with this move.
