### ISSUE TITLE
Issue while installing Senzing in Centos 7

### ISSUE THREAD

**Issue by SaravananKalimuthu21** [Senzing/docker-compose-demo#87]
Hi Michael,

We were trying to install the senzing using docker compose guide with this https://github.com/Senzing/docker-compose-demo/blob/master/docs/docker-compose-rabbitmq-postgresql/README.md

We got some issues while installing that.

**Error:**
senzing-yum | Loaded plugins: fastestmirror, ovl
senzing-yum | Loading mirror speeds from cached hostfile
senzing-yum | * base: repos.lax.layerhost.com
senzing-yum | * extras: mirrors.ocf.berkeley.edu
senzing-yum | * updates: mirror.shastacoe.net
senzing-yum | Resolving Dependencies
senzing-yum | --> Running transaction check
senzing-yum | ---> Package senzingapi.x86_64 0:1.15.3-20141 will be installed
senzing-yum | --> Processing Dependency: senzingdata-v1 >= 1.0.0 for package: senzingapi-1.15.3-20141.x86_64
senzing-yum | --> Running transaction check
senzing-yum | ---> Package senzingdata-v1.x86_64 0:1.0.0-19287 will be installed
senzing-yum | --> Finished Dependency Resolution
senzing-yum | Dependencies Resolved
senzing-yum | ================================================================================
senzing-yum | Package Arch Version Repository Size
senzing-yum | ================================================================================
senzing-yum | Installing:
senzing-yum | senzingapi x86_64 1.15.3-20141 senzing-production 449 M
senzing-yum | Installing for dependencies:
senzing-yum | senzingdata-v1 x86_64 1.0.0-19287 senzing-production 766 M
senzing-yum | Transaction Summary
senzing-yum | ================================================================================
senzing-yum | Install 1 Package (+1 Dependent package)
senzing-yum | Total download size: 1.2 G
senzing-yum | Installed size: 3.1 G
senzing-yum | Downloading packages:
senzing-yum | --------------------------------------------------------------------------------
senzing-yum | Total 46 MB/s | 1.2 GB 00:26
senzing-yum | Running transaction check
senzing-yum | Running transaction test
senzing-yum | Transaction test succeeded
senzing-yum | Running transaction
senzing-yum | ENVIRONMENT SET TO ACKNOWLEDGE ACCEPTANCE of the Senzing EULA at https://senzing.com/end-user-license-agreement
senzing-yum | Error unpacking rpm package senzingdata-v1-1.0.0-19287.x86_64
senzing-yum | Installing : senzingdata-v1-1.0.0-19287.x86_64 1/2
senzing-yum | error: unpacking of archive failed on file /opt/senzing/data/1.0.0: cpio: mkdir
senzing-yum | error: senzingdata-v1-1.0.0-19287.x86_64: install failed
senzing-yum | ENVIRONMENT SET TO ACKNOWLEDGE ACCEPTANCE of the Senzing EULA at https://senzing.com/end-user-license-agreement
senzing-yum | Error unpacking rpm package senzingapi-1.15.3-20141.x86_64
senzing-yum | Installing : senzingapi-1.15.3-20141.x86_64 2/2
senzing-yum | error: unpacking of archive failed on file /opt/senzing/g2/LICENSE;5ee2ac7b: cpio: open
senzing-yum | Verifying : senzingdata-v1-1.0.0-19287.x86_64 1/2
senzing-yum | Verifying : senzingapi-1.15.3-20141.x86_64 2/2
senzing-yum | Failed:
senzing-yum | senzingapi.x86_64 0:1.15.3-20141 senzingdata-v1.x86_64 0:1.0.0-19287
senzing-yum | Complete!

Can you join us for a screen-share? we are available on or after 8AM Friday PST. Will that work for you to join?

Please let us know your availability.

Thanks.

**Comment by docktermj** [comment]
Hi Saravanan!

A couple of ideas based on this error:

> senzing-yum | error: unpacking of archive failed on file /opt/senzing/data/1.0.0: cpio: mkdir

The ultimate issue is the permissions on the directories used for these values:
export SENZING_DATA_DIR=${SENZING_VOLUME}/data
export SENZING_DATA_VERSION_DIR=${SENZING_DATA_DIR}/1.0.0
export SENZING_ETC_DIR=${SENZING_VOLUME}/etc
export SENZING_G2_DIR=${SENZING_VOLUME}/g2
export SENZING_VAR_DIR=${SENZING_VOLUME}/var

If you are on a Mac or Windows, you'll need to follow the "file sharing" steps at https://github.com/Senzing/docker-compose-demo/blob/master/docs/docker-compose-rabbitmq-postgresql/README.md#volumes to give privilege to the directories.

After that, make sure that the directory ownership and permissions are open enough for your userid to use the directories.

Let me know if this help you move forward.

**Comment by SaravananKalimuthu21** [comment]
Sure Michael.. Let us check that.

**Comment by SaravananKalimuthu21** [comment]
Hi Michael,

We tried with the permissions and also tried it by the root user.

We ended up again with the following error

**Error:**
senzing-yum | ENVIRONMENT SET TO ACKNOWLEDGE ACCEPTANCE of the Senzing EULA at https://senzing.com/end-user-license-agreement
senzing-yum | Error unpacking rpm package senzingdata-v1-1.0.0-19287.x86_64
senzing-yum |   Installing : senzingdata-v1-1.0.0-19287.x86_64                            1/2 
senzing-yum | error: unpacking of archive failed on file /opt/senzing/data: cpio: chmod
senzing-yum | error: senzingdata-v1-1.0.0-19287.x86_64: install failed
senzing-yum | ENVIRONMENT SET TO ACKNOWLEDGE ACCEPTANCE of the Senzing EULA at https://senzing.com/end-user-license-agreement
senzing-yum | Error unpacking rpm package senzingapi-1.15.3-20141.x86_64
senzing-yum |   Installing : senzingapi-1.15.3-20141.x86_64                               2/2 
senzing-yum | error: unpacking of archive failed on file /opt/senzing/g2/LICENSE;5ee3b0a6: cpio: open
senzing-yum |   Verifying  : senzingdata-v1-1.0.0-19287.x86_64                            1/2 
senzing-yum |   Verifying  : senzingapi-1.15.3-20141.x86_64                               2/2 
senzing-yum | Failed:
senzing-yum |   senzingapi.x86_64 0:1.15.3-20141      senzingdata-v1.x86_64 0:1.0.0-19287     
senzing-yum | Complete!
[root@uat-app-01 docker-compose-demo]# ls -ltr /opt/senzing/
total 0
drwxrwxrwx. 3 root root 22 Jun 12 16:00 var
drwxr-xr-x. 2 root root  6 Jun 12 16:05 g2
drwxr-xr-x. 2 root root  6 Jun 12 16:05 etc
drwxrwxrwx. 2 root root  6 Jun 12 16:05 data

**Comment by docktermj** [comment]
The latest issue focuses on this error:

> senzing-yum | error: unpacking of archive failed on file /opt/senzing/data: cpio: chmod

This would most likely be a permissions error on the `SENZING_DATA_DIR ` directory.  Which was defined by: 
```
export SENZING_DATA_DIR=${SENZING_VOLUME}/data
```

Check those permissions and opening them up. Wide open would be:
```
sudo chmod 777 -R ${SENZING_DATA_DIR}
```

That will help with fixing the problem, but my be way too open for your production use.  So you'll need to configure your permissions to allow installation, yet doesn't cause exposure problems.

One tact is to use "777" for installation, then use `chmod` and `chown` after the fact to put the proper permissions on the files and directories.

**Comment by jaymuthus** [comment]
Hi Michael,
     Here is the new permissions:
[root@uat-app-01 docker-compose-demo]# ls -ltr /opt
total 0
drwxrwxrwx. 6 root root 50 Jun 12 17:30 senzing
[root@uat-app-01 docker-compose-demo]# ls -ltr /opt/senzing/
total 0
drwxrwxrwx. 2 root root  6 Jun 12 16:05 g2
drwxrwxrwx. 2 root root  6 Jun 12 16:05 etc
drwxrwxrwx. 2 root root  6 Jun 12 17:30 data
drwxrwxrwx. 4 root root 38 Jun 12 22:47 var
[root@uat-app-01 docker-compose-demo]# ls -ltr /opt/senzing/data/
total 0
[root@uat-app-01 docker-compose-demo]# 

**But still getting the below error:**

senzing-yum | Loaded plugins: fastestmirror, ovl
senzing-yum | Loading mirror speeds from cached hostfile
senzing-yum |  * base: centos.s.uw.edu
senzing-yum |  * extras: linux.mirrors.es.net
senzing-yum |  * updates: centos.s.uw.edu
senzing-yum | Resolving Dependencies
senzing-yum | --> Running transaction check
senzing-yum | ---> Package senzingapi.x86_64 0:1.15.3-20141 will be installed
senzing-yum | --> Processing Dependency: senzingdata-v1 >= 1.0.0 for package: senzingapi-1.15.3-20141.x86_64
senzing-yum | --> Running transaction check
senzing-yum | ---> Package senzingdata-v1.x86_64 0:1.0.0-19287 will be installed
senzing-yum | --> Finished Dependency Resolution
senzing-yum | Dependencies Resolved
senzing-yum | ================================================================================
senzing-yum |  Package            Arch       Version             Repository              Size
senzing-yum | ================================================================================
senzing-yum | Installing:
senzing-yum |  senzingapi         x86_64     1.15.3-20141        senzing-production     449 M
senzing-yum | Installing for dependencies:
senzing-yum |  senzingdata-v1     x86_64     1.0.0-19287         senzing-production     766 M
senzing-yum | Transaction Summary
senzing-yum | ================================================================================
senzing-yum | Install  1 Package (+1 Dependent package)
senzing-yum | Total download size: 1.2 G
senzing-yum | Installed size: 3.1 G
senzing-yum | Downloading packages:
senzing-yum | --------------------------------------------------------------------------------
senzing-yum | Total                                               44 MB/s | 1.2 GB  00:27     
senzing-yum | Running transaction check
senzing-yum | Running transaction test
senzing-yum | Transaction test succeeded
senzing-yum | Running transaction
senzing-yum | ENVIRONMENT SET TO ACKNOWLEDGE ACCEPTANCE of the Senzing EULA at https://senzing.com/end-user-license-agreement
senzing-yum | Error unpacking rpm package senzingdata-v1-1.0.0-19287.x86_64
senzing-yum |   Installing : senzingdata-v1-1.0.0-19287.x86_64                            1/2 
senzing-yum | error: unpacking of archive failed on file /opt/senzing/data: cpio: chmod
senzing-yum | error: senzingdata-v1-1.0.0-19287.x86_64: install failed
senzing-yum | ENVIRONMENT SET TO ACKNOWLEDGE ACCEPTANCE of the Senzing EULA at https://senzing.com/end-user-license-agreement
senzing-yum | Error unpacking rpm package senzingapi-1.15.3-20141.x86_64
senzing-yum |   Installing : senzingapi-1.15.3-20141.x86_64                               2/2 
senzing-yum | error: unpacking of archive failed on file /opt/senzing/g2: cpio: chmod
senzing-yum |   Verifying  : senzingdata-v1-1.0.0-19287.x86_64                            1/2 
senzing-yum |   Verifying  : senzingapi-1.15.3-20141.x86_64                               2/2 
senzing-yum | Failed:
senzing-yum |   senzingapi.x86_64 0:1.15.3-20141      senzingdata-v1.x86_64 0:1.0.0-19287     
senzing-yum | Complete!

**Comment by docktermj** [comment]
The line of interest is :
```
https://github.com/Senzing/docker-compose-demo/issues/87
```
Can you show me the values for these variables:
```
echo $SENZING_VOLUME
echo $SENZING_DATA_DIR
echo $SENZING_DATA_VERSION_DIR
echo $SENZING_ETC_DIR
echo $SENZING_G2_DIR
echo $SENZING_VAR_DIR
```
Also output from
```
ls -la $SENZING_VOLUME
```

**Comment by jeffadair** [comment]
I ran into this today on CentOS 7, and I figured out that SELinux was preventing it from installing Senzing. If I disabled SELinux it ran without error.

I did "setenforce 0" to temporarily disable SELinux. Give that a try and see if it helps you.

**Comment by jaymuthus** [comment]
yes @jeffadair, @SaravananKalimuthu21 has installed it today by disabling this flag SELinux.

I wanted to know if we can install it without disabling the SELinux as well. 
Also, when we install it to our clients, I am not sure, will they agree to disable it or not?

After the installation, if we enable SELinux, will everything work fine?

**Comment by jaymuthus** [comment]
@docktermj Will redo the steps again by enabling that flag and give you the data.

**Comment by docktermj** [comment]
@jaymuthus We haven't done any specific testing with SELinux.   That said, because you are running Senzing in containers,  you'll have to consider SELinux from a Docker perspective. In addition, there are four Senzing `--volume` mounts you will have to account for in your SELinux policies.

As for Docker itself, searching on "selinux and docker" returns articles such as:

1. https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html/container_security_guide/docker_selinux_security_policy
2. https://www.projectatomic.io/docs/docker-and-selinux/
3. https://medium.com/lucjuggery/docker-selinux-30-000-foot-view-30f6ef7f621

**Comment by SaravananKalimuthu21** [comment]
Thanks Michael,

I think we can close this issue here.

**Comment by jaymuthus** [comment]
Thanks Michael, we will check that.

**Comment by docktermj** [comment]
@SaravananKalimuthu21 , @jaymuthus I'm glad things are working out.  Do close this GitHub issue when you are satisfied.
