### ISSUE TITLE
Prepare for Senzing release 2.0.0

### ISSUE THREAD

**Issue by docktermj** [Senzing/docker-compose-demo#96]
**Is your feature request related to a problem? Please describe.**
senzing 2.0.0 is coming.  In preparation for it, create a final version that works with senzing 1.x.x

**Comment by docktermj** [comment]
Pull requests

1. https://github.com/Senzing/docker-compose-demo/pull/97

**Comment by arawinters** [comment]
I am unfamiliar with what's going on in this view. Are you just trying to lock versions?
